version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/docker-image-tags.json
      - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Packages
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Check Formatting
          command: yarn prettier:ci
      - run:
          name: Test
          command: yarn test
